### PR TITLE
added markdown code block highlighting

### PR DESCRIPTION
**Pull request by cardboardboxpepe**
added the CS tag for C# syntax highlighting

### CODE REVIEW

**Comment by TalAloni** [comment]
Thanks, too bad there is no immediate preview. I will take a look later.

**Comment by cardboardboxpepe** [comment]
> Thanks, too bad there is no immediate preview. I will take a look later.

You should be able to view the changed file in my own repo, [here](https://github.com/cardboardboxpepe/SMBLibrary/blob/patch-1/ClientExamples.md).

**Comment by TalAloni** [comment]
Thanks!

**Comment by cardboardboxpepe** [comment]
no problem, I'm a stickler for linting the code in markdown

**Pull request merged**
