### PR TITLE
Throw TimeoutException instead of returning null

### PR DESCRIPTION
**Pull request by jtirjan**

### CODE REVIEW

**Comment by TalAloni** [comment]
I'll have to think about it.
Also note that it would be the first usage of String interpolation using $ in this project, currently I'm maintaining C# 2.0 compatibility due to historic reasons, it's probably not needed anymore though, but I will not break it over a small thing.

**Comment by KieranDevvs** [comment]
> Thanks, I'll have to think about it. Also note that it would be the first usage of String interpolation using $ in this project, currently I'm maintaining C# 2.0 compatibility due to historic reasons, it's probably not needed anymore though, but I will not break it over a small thing.

When are you going to ever use a version of the compiler before 2005? The compiler is backwards compatible all the way to 1.0. There is no reason to target a language version earlier than the lowest target runtime which in this case is .NET framework 4.0. That means at a ***bare minimum*** you should be targeting 7.3 and even that isn't required because 99% of language features don't require runtime capabilities.

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults

**Comment by TalAloni** [comment]
Hi Kieran,
1. VS2005 support was dropped last week, you can now use string interpolation using $.
2. I'm still not sure if I prefer throwing an exception or returning NTStatus.STATUS_INVALID_SMB, I'm leaning towards throwing an exception though.

**Comment by TalAloni** [comment]
In principle you are right, if the server fails to respond in time the exception should be TimeoutException.
In practice however it makes the client sample code longer (and I have an issue when first establishing connection where it may seem like a timeout but it's actually not an SMB server). it's also a breaking change.
So I'm not 100% there yet.

**Comment by jtirjan** [comment]
Hi @TalAloni,

As a somewhat less breaking alternative, would you be open to returning `STATUS_IO_TIMEOUT = 0xC00000B5` instead?
That would still allow me to implement timeout-specific handling in my consuming code, just like if the SMB server itself returned that status.
My issue with the current implementation is that I can't differentiate whether `STATUS_INVALID_SMB` responses are truly bad calls, or just timeouts which can be retried.

Thanks!
Jon

**Comment by TalAloni** [comment]
Hi Jon,
I am 100% on board with the principle that if a command is sent to the server and the server does not reply, then STATUS_IO_TIMEOUT is the appropriate status to be returned.
However, if the server has disconnected the connection or returned something that does not comply with the SMB specifications, then it should be STATUS_INVALID_SMB.

Right now we don't interrupt the mechanism that waits for reply if the connection has been terminated, and that's something I want to address.

Once that's done - we can communicate to the user of the library whether we are dealing with STATUS_IO_TIMEOUT or STATUS_INVALID_SMB.

BTW, and that's a bit of topic and more of a personal curiosity, I would expect that one would know their servers and network and would set the appropriate timeout rather then implement a retry mechanism. am I wrong here?

**Comment by jtirjan** [comment]
> BTW, and that's a bit off-topic and more of a personal curiosity, I would expect that one would know their servers and network and would set the appropriate timeout rather then implement a retry mechanism. am I wrong here?

One of my use-cases is to help customers migrate files from a NAS to the cloud. I need to scale out and try to complete the transfer as fast as possible, which can overwhelm the NAS. Identifying timeouts is important not only for knowing when to retry, but also for auto-throttling.

**Comment by TalAloni** [comment]
Hi Jon,
I've pushed the changes we discussed. Let me know if this helps.

**Comment by TalAloni** [comment]
STATUS_IO_TIMEOUT is used when applicable starting from v1.5.3.

**Comment by jtirjan** [comment]
> Hi Jon, I've pushed the changes we discussed. Let me know if this helps.

Thanks @TalAloni! I'm going to try out moving to the 1.5.3 nuget

**Pull request closed without merging**
