### PR TITLE
在查询列表接口中的入参中加入身份信息。存在和文件系统不一样的需求，不能看到自己没有权限的文件。而不是看到了不能使用。

### PR DESCRIPTION
**Pull request by tanlng**
在查询列表接口中的入参中加入身份信息。
存在和文件系统不一样的需求，不能看到自己没有权限的文件。而不是看到了不能使用。

### CODE REVIEW

**Comment by TalAloni** [comment]
1. I do not understand Chinese.
2. SecurityContext is available through SMB1Session / SMB2Session - so there is no need for this change IMO

**Comment by tanlng** [comment]
I tried to implement the INTFileStore interface but failed to use SMB2Session.
The modifier for SMB2Session is internal
2. Unable to obtain the SessionID
3. There is no SMB2ColutionState object

**Comment by tanlng** [comment]
I have some customized requirements for SMB servers. There is a requirement that is different from a file system, where one cannot see files that they do not have permission for, rather than seeing files that cannot be used. So it is necessary to add user information in the QueryDirectory method of the INTFileStore interface.

**Comment by TalAloni** [comment]
My previous response wasn't clear - sorry,
There are ways to achieve your requirements without making unnecessary changes to the library.
Notice that INTFileStore.CreateFile accept the SecurityContext argument.
You should store it for the handle and use it when QueryDirectory is issued on the handle.

**Comment by tanlng** [comment]
Thank you, this can solve my problem

**Pull request closed without merging**
