### PR TITLE
Exposes client connection and logged in state to the public API

### PR DESCRIPTION
**Pull request by KieranDevvs**
Currently, consumers of the client API's have to store and track the client state themselves when the client already contains this data. This pull request exposes these properties on the client interface and updates v1 & v2 of the SMB clients to expose their internal state via the interface.

### CODE REVIEW

**Comment by TalAloni** [comment]
Hi Kieran,
Thanks for the pull request,
Given that you get a clean indication during the Connect and Login phase whether those operations were successful, it's not clear to me where this information is going to be useful, could you please shed light on this? in which scenario those properties are helpful?

**Comment by KieranDevvs** [comment]
Its the same reason `System.Net.Socket` has the public property `Connected` https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.connected?view=net-6.0

**Comment by KieranDevvs** [comment]
@TalAloni Can I get an update on this please?

**Comment by TalAloni** [comment]
Hi Kieran,
I apologize, I've taken a few responsibilities and I can't seem to find the time to give thought this non-urgent request. I hope I'll find the time in the coming weeks.

**Comment by KieranDevvs** [comment]
> Hi Kieran, I apologize, I've taken a few responsibilities and I can't seem to find the time to give thought to this non-urgent request. I hope I'll find the time in the coming weeks.

Ok thanks, appreciate it.

**Comment by TalAloni** [comment]
Hi Kieran,
I've exposed IsConnected given that indeed this property can be changed by the server and may be useful to have available.
Regarding IsLoggedIn - I'm not sure I see as much value in that given that the client is in complete control of the login which should immediately follow the Connect phase (i.e. the server cannot Logoff a user - only to disconnect the connection).
I hope this helps. thank you.

**Comment by KieranDevvs** [comment]
@TalAloni Looks like something is wrong with the 1.4.9 release, your changes don't appear to be in that release binary or source code.

**Comment by TalAloni** [comment]
These changes were merged after the 1.4.9 release (I've remembered about them after already releasing 1.4.9).

**Pull request closed without merging**
