### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by tibel**
- SDK style projects
- .NET Standard 2.0

### CODE REVIEW

**Comment by TalAloni** [comment]
Thanks,
I am thinking about upgrading the project in a way that will still allow me to target .NET Framework 2.0 as well as .NET Standard 2.0.
didn't have much time to figure this out lately, I'm going to get to it eventually.

**Comment by tibel** [comment]
This should be possible with multi-targeting. Before you supported net40 why you want net20?

**Comment by tibel** [comment]
I'm more interested in .NET Standard to use with with .NET Core on Linux

**Comment by TalAloni** [comment]
Thanks, I'm also considering having the two sln / csproj files side-by-side for a while. (like BouncyCastle does).
I have a few hectic weeks, I will try to find the time to make sure I don't break support for anything important. thanks in advance for your patience.

**Comment by TalAloni** [comment]
Sorry, this is on my mind but I need more time to get to it.

**Comment by TalAloni** [comment]
Thanks for this,
I have now added VS2019 solution and (SDK style) projects while keeping the existing VS2005 ones (for the time being).
I've added .NET Standard 2.0 target as well as .NET Framework 2.0 and 4.0
I've relied on your PR and it was very helpful, but could not commit it as-is, really appreciate the push in the right direction.

**Pull request closed without merging**
